# Generated by Django 3.1.7 on 2021-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('category', models.CharField(blank=True, choices=[('technical', 'техника'), ('product', 'продукты'), ('things', 'вещи')], max_length=200, null=True)),
            ],
        ),
    ]
