# Generated by Django 3.1.7 on 2021-05-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='webapp.order'),
        ),
    ]
